### ISSUE TITLE
Ingress rewrite target not including function namespace

### ISSUE THREAD

**Issue by goncalo-oliveira** [justfaas/faas-operator#1]
When a function is deployed with an ingress spec, an ingress object is created. The rewrite target should point to the function's proxied path.

However, when the function is deployed in a namespace, the rewrite target is not properly written and doesn't include the namespace.

Example function YAML

```yaml
apiVersion: justfaas.com/v1alpha1
kind: Function
metadata:
  name: hello
  namespace: my-namespace
spec:
  image: gcr.io/google-samples/hello-app:1.0
  ingress:
    host: hello.example.com
```

The expected ingress YAML

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /proxy/my-namespace/hello/$1
```

However, this is what we get instead

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /proxy/hello/$1
```
